class ServerException implements Exception{}
class WeakPasswordException implements Exception{}
class EmailAlreadyInUseException implements Exception{}
class UserNotFoundException implements Exception{}
class WrongPasswordException implements Exception{}
class GmailAuthException implements Exception{}
class FacebookAuthException implements Exception{}
class VerificationBySendEmailException implements Exception{}
class UpdatePasswordException implements Exception{}
class OfflineException implements Exception{}