const String SERVER_FAILURE_MESSAGE = 'Please try again later .';
const String EMPTY_CACHE_FAILURE_MESSAGE = 'No Data';
const String OFFLINE_FAILURE_MESSAGE = 'Please Check your Internet Connection';
const String USER_NOT_FOUND_FAILURE_MESSAGE = 'No user found for that email.';
const String WRONG_PASSOWORD_FAILURE_MESSAGE = 'Wrong password provided for that user.';
const String GMAIL_AUTH_FAILURE_MESSAGE = 'Gmail auth is has exception.';
const String FACEBOOK_AUTH_FAILURE_MESSAGE = 'Facebook auth is has exception.';
const String VERIFICATION_BY_EMAIL_FAILURE_MESSAGE = 'Verfication by email is has exception.';
const String UPDATA_PASSWORD_FAILURE_MESSAGE = 'Updata password is has exception.';
